### ISSUE TITLE
Feedback: Project Management

### ISSUE THREAD

**Issue by ivanmilara** [kecheeng/example-repository#3]
Hi Kecheng, 

Very good job. It is really an achievement that without any background you managed to build a website in such short time. Congratulations!

Still there are few things that you should clarify in order we can accept this assignment. One important thing, sometimes pictures are not enough to present all the knowledge. You should include some textual explanations. 

One recomentat
# Principles and Practice Feedback #

## From Assessment guide ##

* [x] Sketched your final project idea/s
* [x] Described what it will do and who will use it

### About your website ###

You are using the default mkdocs theme. The structure is clear and you have all required sections. 

### About your project ###

It meets the course requirements, and can be perfectly design and built at Fab Lab. Furthermore, it does not have too much complexity so I think is suitable for your skills. 

# Project Management #
## From Assessment guide ##

* [ ] Made a website and described how you did it
* [x] Created a section about yourself on that website
* [x] Added a page with a sketch and description of your final project idea(s)
* [ ] Documented steps for creating your Git repository and adding files to it
* [x] Pushed to the class GitLab

### About me website ###

It is OK. Perhaps you might want to change the social media links at the bottomo of the page. If someone would like to contact you would be nice to have your information up-to-date.

### Description of the GIT process ###
* Give a short introduction what is GIT and what is Github.
*  Explain how did you configure "Pages" in github to update the website. 
*  Explain how did you upload the structure of your repository, so pages are deployed. 
*  You should define a public/private SSH key pair and identify with that. Explain how you created the public/private key and how you configured Github. 

### Description of the website ###
* Explain how you built your site. What is an static site generator? What static site generator did you use? What is a template? What template did you use?
* Explain how did you modified your site. What is markdown? Summarize markdown syntax (e.g. how did you add images?)
* Explain how did you use Mkdocs: what is `mkdocs build`? What is `mkdocs serve`? What is a `localhost`?
* Explain the role of `mkdocs.yml`. How did you modify it?

**Comment by kecheeng** [comment]
Hi Ivan,

Thank you for your feedback.

Actually I wasn't fully prepared the documentation because I was finding time writing the textual parts, so I hadn't sent the link to you before.

Your scaffold gives me prompts on what and how to write.

I will finish it step by step and catch up by consulting specific parts with you through these weeks.

Please feel free to comment and help me construct the FB portfolio.

Have a nice day.

Best regards,
Kecheng



At 2022-02-23 15:52:42, "Iván Sánchez Milara" ***@***.***> wrote:

Hi Kecheng,

Very good job. It is really an achievement that without any background you managed to build a website in such short time. Congratulations!

Still there are few things that you should clarify in order we can accept this assignment. One important thing, sometimes pictures are not enough to present all the knowledge. You should include some textual explanations.

One recomentat

Principles and Practice Feedback
From Assessment guide
Sketched your final project idea/s
Described what it will do and who will use it
Comments
About your website

You are using the default mkdocs theme. The structure is clear and you have all required sections.

About your project

It meets the course requirements, and can be perfectly design and built at Fab Lab. Furthermore, it does not have too much complexity so I think is suitable for your skills.

Project Management
From Assessment guide
Made a website and described how you did it
Created a section about yourself on that website
Added a page with a sketch and description of your final project idea(s)
Documented steps for creating your Git repository and adding files to it
Pushed to the class GitLab
Comments
About me website

It is OK. Perhaps you might want to change the social media links at the bottomo of the page. If someone would like to contact you would be nice to have your information up-to-date.

Description of the GIT process
Give a short introduction what is GIT and what is Github.
Explain how did you configure "Pages" in github to update the website.
Explain how did you upload the structure of your repository, so pages are deployed.
Description of the website
Explain how you built your site. What is an static site generator? What static site generator did you use? What is a template? What template did you use?
Explain how did you modified your site. What is markdown? Summarize markdown syntax (e.g. how did you add images?)
Explain how did you use Mkdocs: what is mkdocs build? What is mkdocs serve? What is a localhost?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ivanmilara** [comment]
Hi Kecheng, could you please estimate where your documentation would be ready for checking?

**Comment by ivanmilara** [comment]
Hi Kecheng, 

Very good job. You have really improved your documentation!!!

I also like how you try to translate technical language into something more understandable for eveyrbody. 

Still there are few things that you should clarify in order we can accept this assignment. One important thing, sometimes pictures are not enough to present all the knowledge. You should include some textual explanations. 

One recomentat
# Principles and Practice Feedback #

## From Assessment guide ##

* [x] Sketched your final project idea/s
* [x] Described what it will do and who will use it

## Comments ##

### About your website ###

You are using the default mkdocs theme. The structure is clear and you have all required sections. You have modifed the colors of the them, giving more personalized aspect

### About your project ###

It meets the course requirements, and can be perfectly design and built at Fab Lab. Furthermore, it does not have too much complexity so I think is suitable for your skills. 

# Project Management #
## From Assessment guide ##

* [ ] Made a website and described how you did it
* [x] Created a section about yourself on that website
* [x] Added a page with a sketch and description of your final project idea(s)
* [ ] Documented steps for creating your Git repository and adding files to it
* [x] Pushed to the class GitLab

## Comments ##

### About me website ###

It is OK


### Description of the GIT process ###

* You say: 
> I must type mkdocs build every time manually

Explain why this is happening. Basically, Github does not support mkdocs, so you need to convert markdown into HTML in your own computer. This operation cannot be done remotely, like it is possible in Gitlab. 

* In Step 6: There is a misconception in hte figure. 
  - `git add`: Prepare the files to be commited (track those files)
  - `git commit` :Store the files that has been added to the local reposiotry
  - `git push`: synchronize local repository with remote repository. All changes in local repository will moved ot remote repository  

*  Explain a bit how Pages work. What is the folder that is deployed as the website (hint: it is tje /docs)
* In step 9: which is the file that you are showing there? I think it is `mkdocs.yml` you need to mention it. 
* In step 10: explain what is stored in `_docs` and what in `docs` folder. Since in your `mkdocs.yml` you have: 
  * docs_dir: _docs -> It means that you source code, that is your markdown, is stored in this folder
  * site_dir: docs -> It means your HTML code built using mkdocs is stored in docs folder (it is actually the folder that your deploying using the Pages) 

* In SSH (Stage 1) there is one image that does not appear `!{}(../images/ssh1.png)`

### Description of the website ###

* In markdown (stage 2) you need to escape the characters in order to show the syntax. For that, you should use  \

For instance if you want to show  \*\*xxx\*\* you should write \ before each asterisks. 

Furthermore you say for instance three start dots: create a vertical line. But you write \*\* three start dots -> Where are the e start dots?

Finally the last element in the list \[\]\(\) is to create a link

* In markdown (Stage2) you say: 

> Markdown language is commonly used in many modern webpages, where you can directly type some dots to change the elements of texts.

I do not understand what you mean there, and I do not understand the pictures you attach later. 

* `mkdocs build` should be utilized before you want to update the website, and you should do the whole process: `git add, git commit, git push`

* Explain what is an static site generator? What static site generator did you use? What is a template? What template did you use?
* Explain how did you use Mkdocs: what is `mkdocs build`? What is `mkdocs serve`? What is a `localhost`?
* Explain the role of `mkdocs.yml` in mkdocs. 


In relation to your question in the e-mail. If you want to previsualize the website using http:\\localhost:8000 you need to use `mkdocs serve`

With respect to the switch, sincerelly I do not know. I have not done it before. Your code looks correct, I would need to explore it more deeply. I will let you know when I manage to find out the problem.

**Comment by ivanmilara** [comment]
Hi Kecheng, 

Almost there. Just minor clarifications are needed.

* Step 3 does not belong to SSH anymore.  You can create a new title there name: Creating the site
* Step 4: could you explain better what do you mean with "personal local repository"-> how have you created that repository? Sentence is not clear
* Step 6: From where you cut index.html and styel.csss
* Step 7: You create the remote repository. But then, you must push your local repository to the remote, right?. Otherwise, how would you see a website in Step 8?
* Step 11: The Static site generator that you use is Mkdocs. In addition, it is actually that Github requires user to type manually `mkdocs` the real problem is that Github does not support that mkdocs is executed in the server.

**Comment by ivanmilara** [comment]
Hi Kecheng, 

There is still a minor thing that you need to solve. Other than that, you are basically done. Let me know when it is ready.

* Some of the steps in the Creating the site section are wrong: 
  - Step 1 OK
  - Step 2 OK
  - Step 3: You still have not created a repository. You just have a folder. In order to create a repository you need to do `git init`
  - Step 4 OK
  - Step 5: There is no link between local repository and your remote repository. You should do this link by typing in the CMD: `git remote add origin <REMOTE REPO URL>` where <REMOTE REPO URL> can be found in your Github repo.

* `[xxx]():` is just the way of creating hyperlinks. Link to other webpages.

**Comment by kecheeng** [comment]
Hi Ivan,

Finally I understand where your github messages came from lol.

I have modified the documentation as follows:

Step 3: You still have not created a repository. You just have a folder. In order to create a repository you need to do git init
![image](https://user-images.githubusercontent.com/97854712/161101560-4255aa97-b1bf-49cb-92d1-916df94bfafe.png)

Step 5: There is no link between local repository and your remote repository. You should do this link by typing in the CMD: git remote add origin <REMOTE REPO URL> where can be found in your Github repo.
![image](https://user-images.githubusercontent.com/97854712/161101724-7c03b05e-feec-414f-9091-d0df62dd6059.png)

[xxx](): is just the way of creating hyperlinks. Link to other webpages.
![image](https://user-images.githubusercontent.com/97854712/161101865-ac878b12-860e-4810-aa62-5b6b981c7bbb.png)

Thank you very much for the guidance. I think it is very meaningful to have f2f classes especially for the first sessions, as you can instantly ask us to retell the logical flows. We can also raise questions while following step on devices. I will be very glad to retake to the VCS session when you have new classes in fablab. 

Kecheng

**Comment by ivanmilara** [comment]
Hei Kencheng. Great work! Now everything seems to be ready. Just one minor thing that you should address. In Step 5 it should be clear that you us `git remote` before pushing. I will mark it as done, and communicate it to Jani.

**Comment by kecheeng** [comment]
Hi Ivan,

I have made the revision in Step 5 as below. I do think it is meaningful to retake the VCS session f2f next time to comb all the logical steps. Thank you again for building up the standards of engineering mind and computational thinking, which helps me to continue writing Antti M's input programming documentation. 

![image](https://user-images.githubusercontent.com/97854712/161338402-1b6fa2c1-6b7e-4ec2-b5ce-33a4cd9c5782.png)

Have a nice weekend. 

best regards,
Kecheng
